namespace Croc.Bpc.Sound.Unix 
{ 
    internal enum AudioFormat 
    { 
        S8, 
        U8, 
        S16_LE, 
        S16_BE, 
        U16_LE, 
        U16_BE, 
        S24_LE, 
        S24_BE, 
        U24_LE, 
        U24_BE, 
        S32_LE, 
        S32_BE, 
        U32_LE, 
        U32_BE, 
        FLOAT_LE, 
        FLOAT_BE, 
        FLOAT64_LE, 
        FLOAT64_BE, 
        IEC958_SUBFRAME_LE, 
        IEC958_SUBFRAME_BE, 
        MU_LAW, 
        A_LAW, 
        IMA_ADPCM, 
        MPEG, 
        GSM 
    } 
}
